name: Push commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: |
          cd ./src
          rm worker
          go get 
          go build -v -o ./worker
          pwd
          ls -l
      - uses: actions/checkout@v3
      - name: Commit report
        run: |
          git config --global user.name 'ravariu-eugen'
          git config --global user.email 'eugen.ravariu@stud.acs.upb.ro'
          git add .
          git commit -am "Automated compile"
          git push